apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirest-net8-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apirest-net8-api
  template:
    metadata:
      labels:
        app: apirest-net8-api
    spec:
      containers:
      - name: apirest-net8-api
        image: juanmcorbera/apirest-net8-api:development 
        ports:
          - containerPort: 8080
        env:
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: database  # Se toma del secret
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: user  # Se toma del secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password  # Se toma del secret
          - name: ConnectionStrings__DefaultConnection
            value: "server=mysql;port=3306;database=${DB_DATABASE};user=${DB_USER};password=${DB_PASSWORD}"