apiVersion: v1
kind: Service
metadata:
  name: apirest-net8-api
spec:
  selector:
    app: apirest-net8-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort